name: Production Publish

on:
    push:
        branches: ['master']

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: nima-ca/coblog-api:latest

jobs:
    publish:
        name: Publish Image
        runs-on: ubuntu-latest

        steps:
            - name: 'Create env file'
              run: |
                  touch .production.env
                  echo API_KEY=${{ secrets.ENV_VARIABLES_FILE }} >> .production.env

            - uses: actions/checkout@v3
            - name: Login
              run: |
                  echo ${{ secrets.PAT }} | docker login ghcr.io -u nima-ca --password-stdin
            - name: Build and Publish
              run: |
                  docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} .
                  docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
